
$(function () {
    angular.module("parking",["controller","ui.router"])
        .config(['$stateProvider','$urlRouterProvider',function ($stateProvider,$urlRouterProvider) {
            $urlRouterProvider.otherwise("/");
            $stateProvider
                .state("loginMessage",{
                    url:"/loginMessage",
                    templateUrl:"template/loginMassage.html",
                    controller:"loginMassageContr"
                })
                .state("homePage",{
                    url:"/",
                    templateUrl:"template/homePage/homePage.html",
                    controller:"homePage"
                })
                .state("gateway",{
                    url:"/gateway",
                    templateUrl:"template/gatewaySettings.html",
                    controller:"gatewayContr"
                })
                //代收费信息
                .state("generationInfo",{
                    url:"/generationInfo",
                    templateUrl:"template/generation.html",
                    controller:"generationContr"
                })
                //代开锁
                .state("agentUnlock",{
                    url:"/agentUnlock",
                    templateUrl:"template/agentUnlock.html",
                    controller:"agentUnlockContr"
                })
                //欠费记录
                .state("arrearsRecords",{
                    url:"/arrearsRecords",
                    templateUrl:"template/arrearsRecords.html",
                    controller:"arrearsRecordsContr"
                })
                //停车记录
                .state("parkingRecords",{
                    url:"/parkingRecords",
                    templateUrl:"template/parkingRecord.html",
                    controller:"parkingRecordContr"
                })
                //固定时间升降锁
                .state("fixedTimeLiftLock",{
                    url:"/fixedTimeLiftLock",
                    templateUrl:"template/fixedTimeLiftLock.html",
                    controller:"fixedTimeLiftLockContr"
                })
                //停车费用统计
                .state("parkingfeeStatistics",{
                    url:"/parkingfeeStatistics",
                    templateUrl:"template/parkingfeeStatistics.html",
                    controller:"parkingfeeStatisticsContr"
                })
                //账户信息
                .state("accountInformation",{
                    url:"/accountInformation",
                    templateUrl:"template/accountInformation.html",
                    controller:"accountInformationContr"
                })
                .state("accountDetail",{
                    url:"/accountInformation/accountDetail",
                    templateUrl:"template/accountMssagedetail.html",
                    params: {
                        phone: ''
                    },
                    controller:"accountDetailContr"
                })
                //停车费信息
                .state("parkingfeeInfo",{
                    url:"/parkingfeeInfo",
                    templateUrl:"template/AreaManage/parkingfeeInfo.html",
                    controller:"parkingfeeInfo"
                })
                //设备故障信息
                .state("equipmentFault",{
                    url:"/equipmentFault",
                    templateUrl:"template/AreaManage/equipmentFault.html",
                    controller:"equipmentFault"
                })
                //收费规则设置
                .state("feeCtrl",{
                    url:"/feeManage",
                    templateUrl:"template/FeeCtrl/FeeCtrl.html",
                    controller:"feeCtrl"
                })
                .state("addFee",{
                    url:"/addFee",
                    templateUrl:"template/FeeCtrl/addFee.html",
                    controller:"addFee"
                })
                .state("editFee",{
                    url:"/editFee/:id",
                    templateUrl:"template/FeeCtrl/addFee.html",
                    controller:"addFee"
                })
                //片区设置
                .state("areaCtrl",{
                    url:"/areaCtrl",
                    templateUrl:"template/AreaCtrl/AreaCtrl.html",
                    controller:"areaCtrl"
                })
                .state("addArea",{
                    url:"/addArea",
                    templateUrl:"template/AreaCtrl/addArea.html",
                    controller:"addArea"
                })
                .state("editArea",{
                    url:"/editArea/:id",
                    templateUrl:"template/AreaCtrl/editArea.html",
                    controller:"editArea"
                })
                .state("linkFee",{
                    url:"/linkFee/:id/:ruleId",
                    templateUrl:"template/AreaCtrl/linkFee.html",
                    controller:"linkFee"
                })
                .state("feeDetail",{
                    url:"/feeDetail/:id/:ruleId/:linkId",
                    templateUrl:"template/AreaCtrl/feeDetail.html",
                    controller:"feeDetail"
                })
                //车位设备设置
                .state("parkspaceEquipment",{
                    url:"/parkspaceEquipment",
                    templateUrl:"template/ParkspaceEquipment/ParkspaceEquipment.html",
                    controller:"parkspaceEquipment"
                })
                .state("addPE",{
                    url:"/addPE",
                    templateUrl:"template/ParkspaceEquipment/addPE.html",
                    controller:"addPE"
                })
                .state("editPE",{
                    url:"/editPE/:id",
                    templateUrl:"template/ParkspaceEquipment/addPE.html",
                    controller:"addPE"
                })
                //巡检员设置
                .state("inspectorCtrl",{
                    url:"/inspectorCtrl",
                    templateUrl:"template/InspectorCtrl/InspectorCtrl.html",
                    controller:"inspectorCtrl"
                })
                .state("addIn",{
                    url:"/addIn",
                    templateUrl:"template/InspectorCtrl/addIn.html",
                    controller:"addIn"
                })
                .state("editIn",{
                    url:"/editIn/:id/:pwd",
                    templateUrl:"template/InspectorCtrl/editIn.html",
                    controller:"editIn"
                })
                //统计与展示
                .state("parkingSpaceCurrently",{
                    url:"/parkingSpaceCurrently",
                    templateUrl:"template/StatisticsShow/parkingSpaceCurrently.html",
                    controller:"parkingSpaceCurrently"
                })

        }]);
    angular.bootstrap(document,['parking']);
});